(**** Beginning of end.txt ****)
(*** begin settings ****)
(**** end settings ****)
(**** begin move to cooling position ****)
(**** end move to cooling position ****)
(**** begin cool for safety ****)
M104 S0 T0 (set extruder temperature)
(**** end cool for safety ****)
(**** end of end.txt ****)
